#!/usr/bin/env python
import sys
sys.path.append ("../support")
from pkg_resources import require
require ("offlineimap")
require ("simplejson")

from locale import *
from offlineimap import init
init.startup('6.2.0')
