# ===========================================================================
# Project:   Ui
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore

# Proxys to appengine dev server
proxy "/prefs", :to => "localhost:8081"
